"""add company_id and companies table

Revision ID: 495376efebcb
Revises: 6a66329ddc12
Create Date: 2026-07-02 13:48:37.403875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '495376efebcb'
down_revision: Union[str, None] = '6a66329ddc12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_fetch_logs_company_id'), table_name='fetch_logs')
    op.drop_index(op.f('idx_locations_company_id'), table_name='locations')
    op.drop_index(op.f('idx_reviews_company_id'), table_name='reviews')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_email', table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_reviews_company_id'), 'reviews', ['company_id'], unique=False)
    op.create_index(op.f('idx_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.create_index(op.f('idx_fetch_logs_company_id'), 'fetch_logs', ['company_id'], unique=False)
    # ### end Alembic commands ###

