"""Add multi-tenancy and competitors

Revision ID: 6a66329ddc12
Revises: 20260619_0002
Create Date: 2026-07-02 13:23:43.152739
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6a66329ddc12'
down_revision: Union[str, None] = '20260619_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ai_enable_flag', sa.Boolean(), nullable=False),
    sa.Column('total_enable_review', sa.Integer(), nullable=False),
    sa.Column('analyze_competitor_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_place_id', sa.String(length=255), nullable=False),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('google_reviews_url', sa.Text(), nullable=True),
    sa.Column('target_review_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_place_id', 'company_id', name='uq_competitors_source_place_company')
    )
    op.create_index('idx_competitors_active', 'competitors', ['is_active'], unique=False)
    op.create_index('idx_competitors_company_id', 'competitors', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_company_id', 'users', ['company_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_table('competitor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_place_id', sa.String(length=255), nullable=True),
    sa.Column('external_review_id', sa.String(length=255), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('reviewer_profile_url', sa.Text(), nullable=True),
    sa.Column('reviewer_photo_url', sa.Text(), nullable=True),
    sa.Column('reviewer_local_guide_level', sa.String(length=100), nullable=True),
    sa.Column('reviewer_total_reviews', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('review_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_relative_time', sa.String(length=100), nullable=True),
    sa.Column('review_language', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('owner_response_text', sa.Text(), nullable=True),
    sa.Column('owner_response_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_comp_reviews_rating'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_hash')
    )
    op.create_index('idx_comp_reviews_competitor_id', 'competitor_reviews', ['competitor_id'], unique=False)
    op.create_index('idx_comp_reviews_review_hash', 'competitor_reviews', ['review_hash'], unique=False)
    op.create_index('idx_comp_reviews_review_time', 'competitor_reviews', ['review_time'], unique=False)
    op.add_column('fetch_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fetch_logs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('locations', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('reviews', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'company_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'company_id')
    op.drop_constraint(None, 'fetch_logs', type_='foreignkey')
    op.drop_column('fetch_logs', 'company_id')
    op.drop_index('idx_comp_reviews_review_time', table_name='competitor_reviews')
    op.drop_index('idx_comp_reviews_review_hash', table_name='competitor_reviews')
    op.drop_index('idx_comp_reviews_competitor_id', table_name='competitor_reviews')
    op.drop_table('competitor_reviews')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_company_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_competitors_company_id', table_name='competitors')
    op.drop_index('idx_competitors_active', table_name='competitors')
    op.drop_table('competitors')
    op.drop_table('companies')
    # ### end Alembic commands ###

